// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIFi_NDc8QGFpM7Xtv985thWEUVETsDR4',
    appId: '1:378307680036:web:2064e1b3fb11dec45545b1',
    messagingSenderId: '378307680036',
    projectId: 'zad-aldaia',
    authDomain: 'zad-aldaia.firebaseapp.com',
    storageBucket: 'zad-aldaia.appspot.com',
    measurementId: 'G-N377354YVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-yS4oRCl8Ocw3N3bYio0DhlGipF63-9Y',
    appId: '1:378307680036:android:93aa0abe959929f35545b1',
    messagingSenderId: '378307680036',
    projectId: 'zad-aldaia',
    storageBucket: 'zad-aldaia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYztnOYOkZVU2wHMENeA8nPAc3UaR3ja0',
    appId: '1:378307680036:ios:df282d6f5d5a464d5545b1',
    messagingSenderId: '378307680036',
    projectId: 'zad-aldaia',
    storageBucket: 'zad-aldaia.appspot.com',
    iosBundleId: 'com.example.zadApp',
  );
}
